version: '3.9'

services:
  mysql:
    image: mysql:8.4
    container_name: medvedsson-mysql
    environment:
      MYSQL_DATABASE: crypto_dryrun
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: medvedsson-api
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/crypto_dryrun
      API_BASE_URL: http://api:3000
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3000
    ports:
      - '3000:3000'

  pwa:
    build:
      context: .
      dockerfile: Dockerfile
      target: pwa
    container_name: medvedsson-pwa
    depends_on:
      - api
    env_file:
      - .env
    environment:
      API_BASE_URL: http://api:3000
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3000
    ports:
      - '3001:3001'

  adminer:
    image: adminer:4
    container_name: medvedsson-adminer
    depends_on:
      - mysql
    ports:
      - '8080:8080'

volumes:
  mysql_data:
